steps:

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/your-project-id/weather-data-pipeline', '.']
    id: 'Build Image'
    timeout: '1200s' 


  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/your-project-id/weather-data-pipeline']
    id: 'Push Image'

 
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'weather-data-pipeline',
      '--image', 'gcr.io/your-project-id/weather-data-pipeline',
      '--platform', 'managed',
      '--region', 'us-central1',
      '--allow-unauthenticated',  
      '--memory', '512Mi', 
      '--timeout', '900s',  
      '--set-env-vars', 'ENV_VAR_NAME=value'  
    ]
    id: 'Deploy to Cloud Run'


substitutions:
  _PROJECT_ID: your-project-id
  _SERVICE_NAME: weather-data-pipeline
  _REGION: us-central1


timeout: '1200s'
